### ISSUE TITLE
uninitialized constant PocketApi::Connection (NameError)

### ISSUE THREAD

**Issue by srt32** [alexchee/pocket_api#2]
I'm trying to get a simple server going to get the hang of the functionality in the gem and am getting a NameError when I execute `PocketApi::Connection.client_key = API_KEY`

```
uninitialized constant PocketApi::Connection (NameError)
```

Any idea what I'm doing wrong?  Do you have an open source app using the pocket_api gem to which you could point me?  I'd love to see a working example of the gem.

Thanks.  Happy holidays! :santa:

**Comment by adagio** [comment]
Hi @srt32 
  in the first line of your script you need to include the gem.

```
require 'pocket_api'
```

**Comment by alexchee** [comment]
Sorry, I haven't looked at this project in a while. Are you still having that problem after @adagio's suggestion? 

I was using this on a project to communicate with Pocket, then I think I switched to this one: https://github.com/turadg/pocket-ruby 

It has more stars and probably more active than this PocketApi gem. I don't have a sample repo that uses this gem yet.

**Comment by adagio** [comment]
Thank you @alexchee , for the information. Today I have worked with pocket-ruby, and got this

![pocket-tagging-stats](https://cloud.githubusercontent.com/assets/8528/4779042/e813fa96-5c12-11e4-8b11-e8b11ca08eeb.png)

here is the code -> https://github.com/HartasCuerdas/ruPocket
